# Generated by Django 3.2 on 2023-04-30 22:43

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230429_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre_title',
            options={'ordering': ('title',), 'verbose_name': 'Жанр произведения', 'verbose_name_plural': 'Жанры произведения'},
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[reviews.validators.validate_year], verbose_name='Год выхода'),
        ),
    ]
